
[general]
import = [
"~/.config/alacritty/kanagawa.toml"
]

[font]
size = 24.0

[font.normal]
family = "MesloLGS Nerd Font Mono"

[window]

startup_mode = "Maximized"

decorations = "None"
padding = { x = 20, y = 20 }


