
[general]
import = [
# "~/.config/alacritty/kanagawa.toml"
"~/.config/alacritty/melange.toml"
]

[font]
size = 24.0

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "FiraCode Nerd Font Mono"
# family = "Iosevka Nerd Font"



[window]
startup_mode = "Maximized"

decorations = "None"
padding = { x = 8, y = 8}
